name: Run Shell commands
on: [push]

jobs:
    run-shell-commands:
        runs-on: ubuntu-latest
        steps: 
            - name : Echo a string
              run: echo "This is my first GitHub Actions workflow file"
